// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/ntpSimulation.proto

package ntpSimulation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NtpClient is the client API for Ntp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NtpClient interface {
	GetTime(ctx context.Context, in *SendTime, opts ...grpc.CallOption) (*SendTime, error)
}

type ntpClient struct {
	cc grpc.ClientConnInterface
}

func NewNtpClient(cc grpc.ClientConnInterface) NtpClient {
	return &ntpClient{cc}
}

func (c *ntpClient) GetTime(ctx context.Context, in *SendTime, opts ...grpc.CallOption) (*SendTime, error) {
	out := new(SendTime)
	err := c.cc.Invoke(ctx, "/ntpSimulation.ntp/getTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NtpServer is the server API for Ntp service.
// All implementations must embed UnimplementedNtpServer
// for forward compatibility
type NtpServer interface {
	GetTime(context.Context, *SendTime) (*SendTime, error)
	mustEmbedUnimplementedNtpServer()
}

// UnimplementedNtpServer must be embedded to have forward compatible implementations.
type UnimplementedNtpServer struct {
}

func (UnimplementedNtpServer) GetTime(context.Context, *SendTime) (*SendTime, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTime not implemented")
}
func (UnimplementedNtpServer) mustEmbedUnimplementedNtpServer() {}

// UnsafeNtpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NtpServer will
// result in compilation errors.
type UnsafeNtpServer interface {
	mustEmbedUnimplementedNtpServer()
}

func RegisterNtpServer(s grpc.ServiceRegistrar, srv NtpServer) {
	s.RegisterService(&Ntp_ServiceDesc, srv)
}

func _Ntp_GetTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTime)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NtpServer).GetTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ntpSimulation.ntp/getTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NtpServer).GetTime(ctx, req.(*SendTime))
	}
	return interceptor(ctx, in, info, handler)
}

// Ntp_ServiceDesc is the grpc.ServiceDesc for Ntp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ntp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ntpSimulation.ntp",
	HandlerType: (*NtpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getTime",
			Handler:    _Ntp_GetTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ntpSimulation.proto",
}
